comment:
  image:
    repository: viktoriya666/comment
    tag: latest
  service:
    externalPort: 9292
  
post:
  image:
    repository: viktoriya666/post
    tag: latest
  service:
    externalPort: 5000
  
ui:
  image:
    repository: viktoriya666/ui
    tag: latest
  service:
    externalPort: 9292