{
 "title": "UIMonitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "description": "All HTTP requests that UI service receives",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count[1m])",
     "legendFormat": "{{method}} {{path}} {{http_status}}"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with Errors",
   "type": "graph",
   "description": "Rate of UI HTTP Requests with Errors",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])",
     "legendFormat": "{{http_status}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time 95th Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))",
     "legendFormat": "{}"
    }
   ]
  }
 ]
}