global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: 'viktoriya_volferts'