version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
  ui:
    build: ./${IMG_UI}
    image: ${USERNAME}/${IMG_UI}:${VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    build: ./${IMG_POST}-py
    image: ${USERNAME}/${IMG_POST}:${VERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    build: ./${IMG_COM}
    image: ${USERNAME}/${IMG_COM}:${VERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post

volumes:
  post_db:

networks:
  front_net:
  back_net:
